exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length = 120
indent-width = 4
target-version = "py313"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[lint]
select = [
    "I",    # isort
    "E",    # pycodestyle
    "F",    # pyflakes
    "UP",   # pyupgrade
    "YTT",  # sys.version checks
    "B",    # bugbear
    "A",    # builtins
    "C90",  # mccabe
    "N",    # pep8-naming
    "RUF",  # Ruff-specific rules
]

# Allow auto-fix on these codes
fixable = ["ALL"]

# Don't apply lint rules here if only formatting is desired
ignore = []

# Exclude typical files/directories
exclude = ["__pycache__", ".venv", "build", "dist"]

[lint.pep8-naming]
classmethod-decorators = ["classmethod", "pydantic.validator", "pydantic.field_validator", "pydantic.root_validator"]
