blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/ryancswallace/ipc-frontier-py/discussions
    about: Please use GitHub Discussions for open-ended questions or ideas.
